import { Gabarito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";

const geistSans = Gabarito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Gabarito({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "afvlr.web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#FAEDCD]">
        <Navbar/>
        <main className="flex-1">
          {children}
        </main>
        </body>
    </html>
  );
}
